id: P000807
initial_creation_type: ebook
created_at: 5/04/2021
last_modified_at: 24/11/2021
source_metadata:
  title: qwer
  subtitle: ''
  authors:
  - qwerew
  collection: ''
  publisher: ''
  id: '34123'
  cover: tmpr1gzqkqk.jpg
  credit: tmpz_c32sab.jpg
