id: P000807
initial_creation_type: ebook
source_metadata:
  title: qwer
  subtitle: ''
  authors:
  - qwerew
  collection: ''
  publisher: ''
  id: '34123'
  cover: tmpr1gzqkqk.jpg
  credit: tmpz_c32sab.jpg
